language: php
dist: trusty
sudo: false
cache:
  timeout: 1000
  directories:
  - vendor # Composer packages

php:
  - 7.1

addons:
  postgresql: '9.6'

before_script:
  - psql -c 'create database gzero_cms;' -U postgres
  - cp .env.example .env.testing
  - mkdir -p build/logs
  - composer self-update
  - composer install --prefer-dist --no-interaction --no-suggest --no-progress

script:
  - ./vendor/bin/phpmd src/ text phpmd.xml
  - ./vendor/bin/phpcs --standard=ruleset.xml src/ -n --colors # -n no warnings
  - "php vendor/bin/codecept run -c codeception.yml -o \"settings: lint: false\" --coverage --coverage-xml"
  - mkdir -p build/logs
  - cp tests/_output/coverage.xml build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
