sudo: required

language: php

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.5.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - composer install --prefer-source --no-interaction --dev # installing local dependencies to late use
  - cd ../
  # TODO Add version support. Probably we'd need to add platform compatibility version flag in composer.json
  - git clone --depth=10 https://github.com/GrupaZero/platform.git platform
  - cd platform
  - docker-compose up -d
  - docker exec -i -t platform_dev_web_1 composer install -d /var/www/ --prefer-source --no-interaction --dev # platform deps
  - ./scripts/link_package.sh api mount # mounting our repo to latest platform
  - docker-compose restart # we need to restart to refresh mouted packages
  - cd $TRAVIS_BUILD_DIR

script:
  - ./vendor/bin/phpmd src/ text phpmd.xml
  - ./vendor/bin/phpcs --standard=ruleset.xml src/ -n
  - docker exec -it platform_dev_web_1 php /var/www/vendor/bin/codecept run -c /var/www/vendor/gzero/api/codeception.yml --coverage --coverage-xml
  - docker exec -it platform_dev_web_1 mkdir -p /var/www/build/logs
  - docker exec -it platform_dev_web_1 cp /var/www/tests/_output/coverage.xml /var/www/build/logs/clover.xml

after_script:
  - docker exec -it platform_dev_web_1 bash -c "cd /var/www/vendor/gzero/api && vendor/bin/coveralls -v"

matrix:
  fast_finish: true