language: php

php: 
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer self-update
  - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - ./vendor/bin/phpmd src/ text phpmd.xml
 - ./vendor/bin/phpcs --standard=ruleset.xml src/ -n # -n no warnings
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
